### ISSUE TITLE
Let mods of a channel join the bot to said channel with an argument, like `mb join xqc`

### ISSUE THREAD

**Issue by brian6932** [melon095/Melonbot#25]
Endpoints you can use:
[helix](https://dev.twitch.tv/docs/api/reference#get-moderators)
[ivr](https://api.ivr.fi/v2/docs/static/index.html#/Twitch/get_twitch_modvip__channel_)

**Comment by melon095** [comment]
![image](https://user-images.githubusercontent.com/24413121/188944223-494e0285-0c60-4752-88ca-17ed6614d868.png)
