### ISSUE TITLE
An `amount:` arg for `mb 7tv`

### ISSUE THREAD

**Issue by brian6932** [melon095/Melonbot#30]
**Is your feature request related to a problem? Please describe.**
When you query 7TV GQL, you can output all the emote links from the given query depending on how many you ask for with `amount:`, or optionally an `-all` flag if you want to not deal with counts and just return all.

**Describe the solution you'd like**
Well from what you've said, you don't want to send multiple messages in chat like whckbt did, so an alternative to that would be, posting to a markdown paste site like [rentry](https://rentry.co) or [gist](https://gist.github.com) for hyperlinks.

You can see how to do it with rentry [here]( https://github.com/radude/rentry/blob/master/rentry)
You can see how to do it with gists [here](https://docs.github.com/en/rest/gists)

**Describe alternatives you've considered**
If the goal is to not be intrusive, I still think posting multiple messages in chat wouldn't be terrible, given the right implementation. Granted the user is a mod or broadcaster, and granted they've allowed some option like `Enable 7TV Eventsub notification` on the bot's site dashboard.

**Comment by melon095** [comment]
I like it chief, however i would rather not use any third party hosting websites, such as gist or rentry, I will however have it link my website, for example `url/paste/:id`. This endpoint would be able to render markdown, using the `markdown-it` package, already used in command descriptions. 

Also, sending a lot of url's in the chat should be limited to 30 urls (5 per message) and the bot has to be a moderator to allow this.

**Comment by melon095** [comment]
Okay, i don't see this as a beneficial thing honestly, if you want to view a list of emotes, you already have the official website to look at.
